server:
  port: 9422

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: ${IP_ADDRESS:127.0.0.1}
  client:
    service-url:
      defaultZone: http://localhost:9421/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: welcome-service
  cloud:
    loadbalancer:
      retry:
        enabled: false