server:
  port: 9423

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9421/eureka
    fetch-registry: true
    register-with-eureka: true


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # 是否和发现服务进行组合，设置为True之后可以使用应用名称调用服务
      discovery:
        locator:
          enabled: true
      routes:
        - id: welcome
          uri: lb://welcome-service
          predicates:
            - Path=/welcome/**