server:
  port: 9425

token:
  expire: 3600000


spring:
  application:
    name: user-service
  cloud:
    loadbalancer:
      retry:
        enabled: false
  datasource:
    driver-class-name: org.h2.Driver

    # h2 database file location
    url: jdbc:h2:file:./db/db;
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true